### ISSUE TITLE
Manual definition of issuer:{} as a solution for a blocked connection from RP to OP

### ISSUE THREAD

**Issue by kettenbach-it** [travisghansen/external-auth-server#158]
Hi Travis,

I see in the examples, that it is possible to manually put the results of the discovery of `.well-known/openid-configuration`in the config_token.
My question is: will this prevent eas to do a callback to the OP?

Reason for me asking is: 
I have a situation where the OP is inside an intranet and cannot call outside neither can it called from the outside. 
EAS and the service are in the internet.
Will I be able to provide the eas protected service in the internet to the users in the intranet using the OP in the intranet?

**Comment by travisghansen** [comment]
The `eas` implementation of `oauth/oidc` is the `authorization_code` flow. In that flow `eas` *must* be able to communicate with the auth server.

https://auth0.com/docs/get-started/authentication-and-authorization-flow/authorization-code-flow (the diagram there can actually be confusing as to what's *really* happening)

For example `eas` detects the user does not have an `eas` session and so redirects the browser to the auth provider. After authentication the auth provider 'sends' the code back to `eas` indirectly via a browser redirect (it's actually the browser that sends the cod to `eas`, not the auth provider). In turn `eas` sends that code to the auth provider to issue a token and token is returned to `eas` directly at which point `eas` stores it internally and never sends it back to the browser. The short version, for `authorization_code` flow both the browser and `eas` need to be able to communicate with the auth provider.

If the app is an in-house app which you are developing you could alternatively use the `jwt` plugin instead of `oidc` in which case everything could be handled as long as the browser can talk to both the auth provider and `eas` it would function. Depending on your use-case that may or may not be viable/useful though (essentially in-house SPAs).

**Comment by kettenbach-it** [comment]
I think `jwt` won't help. The OP is a gitlab, which run's at a customers intranet.   
The RP is eas running in our cluster.
I want the users of the customers gitlab to be able to access an application in our k8s cluster behind traefik+eas without eas being able to talk to the customers gitlab.

**Comment by travisghansen** [comment]
Ah, very interesting use-case. I'll put some thought into it but `authorization_code` flow is unlikely to be an option.

**Comment by travisghansen** [comment]
Do you need all the token data (authorization) or just authentication?

**Comment by travisghansen** [comment]
I'm guessing without a substantial amount of effort the different flows could be achieved. I'd have to do some testing to confirm but on the surface it seems feasible. In short the browser would send the id/access tokens directly to `eas` and bypass the `code` process so `eas` would never need to reach out to the auth server.

A way would be needed to validate the tokens however to ensure they are signed by the proper authority (you would need to somehow load up the public sign keys from gitlab into eas.

**Comment by kettenbach-it** [comment]
> Do you need all the token data (authorization) or just authentication?

Authentication would be sufficient

> I'm guessing without a substantial amount of effort the different flows could be achieved. I'd have to do some testing to confirm but on the surface it seems feasible. In short the browser would send the id/access tokens directly to `eas` and bypass the `code` process so `eas` would never need to reach out to the auth server.

Yes, that's the way I thought of it.

> A way would be needed to validate the tokens however to ensure they are signed by the proper authority (you would need to somehow load up the public sign keys from gitlab into eas.

... so I had asked if this is the case if you write the `.well-known/openid-configuration` into the eas config.....

But what I also have to say is that the whole thing is not very important.
In Germany, we often have customers who still think it's better to seal off all systems with firewalls and sometimes build obscure constructs because everything on the Internet is always evil.
They have completely abandoned the balance between the need for safety and  for functionality in favour of safety and would rather break everything than run the risk of being "unsafe" (and this in purely theoretical terms).
Most of the time, they don't even realise how much they are destroying. This is the case we here as well.
But it also doesn't make sense to make an effort for such people.

**Comment by kettenbach-it** [comment]
I'll close this issue because it doesn't make much sense to put more effort on this

**Comment by travisghansen** [comment]
I think I’ll reopen until I have a chance to test it out. I actually quite like the idea of supporting such flows and I *think* it could be accomplished with very little code honestly.

**Comment by kettenbach-it** [comment]
Okay! I'm willing to try it out!

**Comment by travisghansen** [comment]
OK, I have a working prototype for this. I have some security concerns about it however. The only ways I can think of to fully ensure the request is:

- enable token introspection (oauth2 or oidc, requires access to the auth provider by `eas`)
- enable and validate userinfo (oidc or provider specific oauth2, requires access to the auth provider by `eas`)
- validate an `id_token` (oidc only, requires access to the auth provider by `eas` using `jwks` OR the public keys can be provided manually)

To validate an `id_token` and verify the `jwt` you can:

- use the `jwks` endpoint of the auth provider

OR

- have the auth provider transfer the public keys to you to deploy with the service

Practically, if the signing keys change frequently and you are NOT using `jwks` (ie: cannot access the auth provider directly as is your case) then the solution would not be effective.

Do you know if they support oidc and if they can give you the public signing keys to verify the tokens? I think you said they are using gitlab which if indeed that is the case then the solution will work. Just have them send you the output of `https://<server>/oauth/discovery/keys`

**Comment by kettenbach-it** [comment]
The manual transfer of these keys into the eas config was also the basic idea of my first request, where I asked for `.well-known/openid-configuration'. Precisely because this would prevent the call to the OP for the purpose of checking the signature.

This here is not the customers gitlab since - right now - I can't access is but the output of our own Gitlab (which is not firewalled):

```
{
  "keys": [
    {
      "kty": "RSA",
      "kid": "udSe3n-4Kubz6sdq_DR-td5XX5tYz_F03QM_g5hKIvM",
      "e": "AQAB",
      "n": "mDM0x2VgDdxOjUtGFCkiYy6K0xKzzV4goExPu9HT5akqy04jhuLyWGiPkChQXrkx9BYHhcVZhiimxxrixvPd6nPwKgnj0pZfM0etz-kYEYiZUjLGfnJ6N8cGu1ZHY2FrxWj91T9W6t1URp7LL9yWMqdtTmAX-E6yyGNJcWB2H_YOk0K3JcNtpmyfR0W2uNz95N7OM0fPI37XT0Gc79YdRFulym6l7YLxKCIPD44ZmVe4-YUYAguw11OpPbrKHHd4c0TAL1rsbOt5_pJDpYmqlRTAKpy97DaqkpdhwQr8GY8zJFO-l2lWfA3vQEJx5g-VAz_ReBxan7ZQNxbqFTN5Sw",
      "use": "sig",
      "alg": "RS256"
    },
    {
      "kty": "RSA",
      "kid": "Yr27qqYfcydqizzyrO52x5Ux485tvQCSBNHPlOFpgC4",
      "e": "AQAB",
      "n": "u0a-pjV9kHp7VubsZuFDq6tJ5f6JJjskKFlaFwb36Ekr-b4Ufox5PlUqp1SfHOztkaMRmIdhqZJKc4PGoQQU1jO8nxU5S3uyz7jQyG-g9X-Glc1e5OAuOayK7M6QFP_u7f6z4PyLYiMQHbXaXmQv8ZrYo9GGo8_IPJba5TfehKCY5tBVdVGkOkwwsWNup760VBtBIuiaPuNzwC75WFuQSz3ekMf60iLQH0OTQPxORWlpdmqotq_fmCfV9P5bw3G9wz9MQquysO5SU1Zcg1ZzLmauH9kCiznNhiL39Lq3Ot9RM6rYue9fsh7JV6vrSi3xFvbRyKCAFyGEWxK_WWS0Fw",
      "use": "sig",
      "alg": "RS256"
    }
  ]
}
```

I tried to figure out using our own Gitlab when these keys are created and if they are recreated sometime.
But I couldn't find it out exakt details.
At least I found out, that we did not create them as a k8s secret at the installation time.

Do you want me to assure that these are fixed during the lifetime of a Gitlab installation?
What else could I check to make sure we don't run into security issues?

As long as these keys are valid and authentic in the local eas config, there will be no problem.
This assumes that the local admin is trustworthy....

**Comment by travisghansen** [comment]
I'm relatively confident gitlab doesn't cycle those without manual intervention. Can you confirm the org who owns the gitlab instance are willing to share those public keys?

**Comment by travisghansen** [comment]
Also it appears gitlab does not support the implicit flow so it may not be feasible: https://docs.gitlab.com/ee/api/oauth2.html

I'm guessing gitlab is using ldap or whatever for it's user store so they would need to setup something like keycloak and create a client id/secret that supports the implicit flow :(

**Comment by kettenbach-it** [comment]
The customer is indeed using ldap as the backend.
He will be sharing the keys, but he won't install Keycloak. At least not publicly, which wouldn't help. He puts everything behind a firewall and lets only http requests secured by a client-certificate through. A theoretical solution would be to make eas do the requests using a certificate. But I think that's a bad style and it'd had to put a private key into eas which I don't like either.
We can test everything with our Gitlab by blocking eas' access to it. (But we don't use ldap)

**Comment by travisghansen** [comment]
Keycloak would only need to be exposed internally (like gitlab itself).

I have some ideas to try using pkce that I think may work (which gitlab supports) so don’t bother with keycloak/implicit flow for now anyway.

**Comment by kettenbach-it** [comment]
Okay!

**Comment by travisghansen** [comment]
I have a fully functioning prototype now that needs a bit of cleanup and then it will be ready to test. This is very simplified but the basic premise is:

1. client tries to access to service as usual
2. browser is redirected to authenticate
3. after authentication the browser uses the `authorization_code` to request a token set (this is opposed to `eas` doing this usually)
4. after the token set is retrieved the browser sends it to `eas` via ajax POST
5. browser is redirected to service endpoint
6. auth occurs as usual and a browser/user-agent provided token is detected, special logic validates/verifies the token (`id_token` is of upmost importance during this step, and the signature must be validated. ie: this is why you need to get the keys from the gitlab instance) The reason this must be validated is because `eas` did not retrieve to token set directly and therefore cannot trust what the browser sent in step 4. 
7. assuming validations pass etc `eas` creates a session per normal

Note that in your scenario `eas` cannot refresh tokens automatically, fetch userinfo, introspect the tokens or anything else that requires communication with the auth provider. You can expire the session when the `id_token` expires if you wish.

In order to facilitate all the above some things have been greatly enhanced including the ability to use `pkce` and `nonce`. An implementation detail is that now rather than storing *actual* `state` in the URL I simply store a pointer to the real `state` data as stored in redis. This allows the `state` data to grow significantly without introducing URLs that are too long for auth servers/browsers to handle.

I have a very busy week ahead but will try to work on this as possible to get something you can test.

**Comment by kettenbach-it** [comment]
Cool!

**Comment by travisghansen** [comment]
This is implemented (not fully documented yet). Review the sample config below however.

The basic premise is:

1. instead of the 'normal' flow where eas requests a token and stores it locally, the new callback url handles the request with browser-side logic
2. after authenticating to the `op` and landing on the new callback endpoint the browser
- does an ajax post to the `op` and retrieves the token set
- does an ajax post to `eas` giving it the tokenset
- redirects the browser to `eas` for continued auth process
3. upon arrival back to `eas` the service will validate the browser
4. it's incredibly important that you enable the `id_token_signature` assertion otherwise there's absolutely no way to ensure the token sent by the browser to `eas` is trusted/untampered

The actual process going on under the hood is slightly more involved, but those are implementation details and the above is overall design.

The below setup uses a client in gitlab that has 'confidential' *NOT* checked, with `read_user`, `openid`, `profile` and `email` scopes selected.

```
gitlab-pkce:
  aud: development
  eas:
    plugins:
      - type: oidc
        issuer:
          discover_url: https://gitlab.../.well-known/openid-configuration
        client:
          client_id: 
          client_secret: 
        nonce:
          enabled: true
          ttl: 600
        pkce:
          enabled: true
          code_challenge_method: S256
        response_types:
          - code
        scopes:
          - openid
          - email
          - profile
        # crucial new endpoint
        redirect_uri: http://eas/oauth/callback-ua-client-code
        features:
          set_cookie_expiry: false
          refresh_access_token: false
          fetch_userinfo: false
          introspect_access_token: false
          authorization_token: id_token
        assertions:
          # openid scope must be included to retrieve an id_token
          id_token_signature:
            enabled: true
            # defaults to issuer jwks endpoint, can be jwks response data or plain shared key/public key
            key:

          exp: true
          nbf: true
          iss: true
          userinfo: []
          id_token: []
        cookie: {}
```

**Comment by kettenbach-it** [comment]
Wow, this is really cool!
I will try this asap when you'll upload a container image supporting this.
The fact that it will be configurable directly with yaml and without signing and encrypting things, will greatly speed up to adoption process!

**Comment by travisghansen** [comment]
Also already available in `next` images :) I'm currently working to support `userinfo` feature now.

**Comment by kettenbach-it** [comment]
I'd prefer to wait until you tell me that's it's stable. I don't have a test environment for these things. I'll have to test in production :-(

**Comment by travisghansen** [comment]
Fair enough. I have no more planned changes now that this is committed: https://github.com/travisghansen/external-auth-server/commit/8258464fd0a23161a98714dc39ed454a3a85de5c

I'll shout out when the image is built and then have you test.

**Comment by travisghansen** [comment]
OK, `next` images are build and what I intend to release but would prefer at least someone else give the new features a try first :) there are so many possible combinations it's hard to make sure I'm covering everything.

**Comment by kettenbach-it** [comment]
I'll try tomorrow. It's already 7pm here in germany!

**Comment by travisghansen** [comment]
Danke! I just had some German friends stay with me for 2 weeks over the holidays :D

**Comment by travisghansen** [comment]
I should note above, you will need to manually define the issuer vs using a discovery URL. I hope that works end-to-end and there's not some weird dependency in there where it tries to reach out.

**Comment by travisghansen** [comment]
Confirmed working:

```
        issuer:
          #discover_url: https://gitlab/.well-known/openid-configuration
          issuer: "https://gitlab"
          authorization_endpoint: "https://gitlab/oauth/authorize"
          token_endpoint: "https://gitlab/oauth/token"
          revocation_endpoint: "https://gitlab/oauth/revoke"
          introspection_endpoint: "https://gitlab/oauth/introspect"
          userinfo_endpoint: "https://gitlab/oauth/userinfo"
          jwks_uri: "https://gitlab/oauth/discovery/keys"

```

**Comment by kettenbach-it** [comment]
Where do I put the keys, if the gitlab is behind a Firewall?

**Comment by travisghansen** [comment]
Copy the `jwks` response and put it in the `key` block of the assertion.

**Comment by kettenbach-it** [comment]
What is "the key block of the assertion"?

**Comment by travisghansen** [comment]
Something like this:

```
        assertions:
          id_token_signature:
            enabled: true
            # defaults to issuer jwks endpoint, can be jwks response data or plain shared key/public key
            key:
              - kty: RSA
                kid: pr5Qv1TIy9aDnBDpoBvpP7kUEJFg6H03gmA9O0Uf76E
                e: AQAB
                n: ykZwnr_yABOqzBLfzV_V8hCk_KD7xE_WYdug43Ea1LhRTbK3hXrrGv-LbFT2EeWxejT2IeYGbYigmqsOdSMQQ0ieZSzNurzLw3HPDV09hYIrUlCNVOCRyGQzphuIL6Eg5w98S7dyyUtLmmhrluyjMT2c2SwNNXX4h2e7WWs6z6X5nlTLgybeowWN3RbSu35snuN2dFFS_mq0K_F9IZfQ84DYkmlrlV6Q3tyt4hfg6dHyclC4Nd3G8KFv6XkdvqdkntUYoTKnffP0MSrtocVFlYlbQ69YKgPzCs9L_deb6E3Wk3sqr_72Vam7LQzG10gj93-AY-oHj0i_feo2W_7fAZRvg9r7hZVS79T5ecL_-86dCBRjqJQjq6_bPjIItqttEXsF_jIE-kNap93QLItsbRk4YvL7X9CWzfbFUpqau1zcuvAEtS2rDvFWiKQPEztKBwOqVSWJi-DR0Dhw2vKRGEOK6UG1_DtSbrfV7p5dNxxOVrt2VwPCalzGA2k6jLf8mBpxmv4vAd07k6sA_ypZ637TZ2qlvxco4xWAkjIUodoWh-qprTpiJi-M7anRXlZ2X8OxQu4AM5OuvkzCFsCxUE3Fi5hAg9AgwshhnzgI5g9QdqN_iAGKgcesd6rhydf8siqqv-5kOwXcf3_sILakzhWNOw1C8vEHl8i01veqedk
                use: sig
                alg: RS256
              - kty: RSA
                kid: PBZGPLRbLoh1S3pDHPMZUkchzIy0s8iV8WDvXUG_iZg
                e: AQAB
                n: zXBSrPeF42uf54_eHIrq-ot3LpU7prtnGPENg-3SovokiiW8El5q-v_W-1KPM9EugLWpqY9Hdg4ZXGGm3v0W3jPAzSc0Y7M-kT_lSALSg6kws-K0l4pKX0O6rpFQMUUb92pPzZsgrOfYSNKvbd-WtYldXBq2CJRqI8gWC4zKrQIVveN3d__VewuKIIOgwQyxi5iQi935djsqvdkiSRZWjYg6zwrYwJDgAIaM_6eyuWeACbZ1HGI7IlrSb8F7Djl7xk1AwPfsHgW9Sak9RcDNwbGs1NlR6yA-vBKk8IvFR89t-UTrKO8woTDCWMNDOgMOhXtN91u-67vQI1S0-K95EQ
                use: sig
                alg: RS256
```

**Comment by kettenbach-it** [comment]
Okay, first try:

- Setup client in Gitlab:
<img width="1266" alt="image" src="https://user-images.githubusercontent.com/7711872/213715165-be272004-ca78-4ea8-9d86-0fa083bd2dbd.png">

- Created new config token for gitlan hidden behind firewall using the client-id and secret and the contents of the discover URL
<img width="236" alt="image" src="https://user-images.githubusercontent.com/7711872/213715322-377469e0-4dac-4289-967b-c4cb964ba233.png">

- Secured the webservice with eas using the config token

Result:
- Got redirected to Gitlab
- Clicked authrorize
- Got redirected
- Got 501

Error message:

```
external-auth-server 2023-01-20T15:00:11.508774343+01:00 {"code":"UNABLE_TO_VERIFY_LEAF_SIGNATURE","level":"error","message":"unable to verify the first certificate","service":"external-auth-server","stack":"Error: unable to verify the first certificate\n    at TLSSocket.onConnectSecure (node:_tls_wrap:1539:34)\n    at TLSSocket.emit (node:events:513:28)\n    at TLSSocket._finishInit (node:_tls_wrap:953:8)\n    at TLSWrap.ssl.onhandshakedone (node:_tls_wrap:734:12)","timestamp":"2023-01-20T14:00:11.508Z"}
```

**Comment by kettenbach-it** [comment]
They customer uses some kind of shitty certificate which doesn't seem to know to a lot of clients (e.g. most open source tools)

**Comment by travisghansen** [comment]
Can you send your full config token (minus secrets)? I think you may still have something off on the config.

**Comment by kettenbach-it** [comment]
```
gitlab-customer:
      aud: Gitlab-Customer
      eas:
        plugins:
          - type: oidc
            issuer:
              #discover_url: https://wt-repository.customer.de/.well-known/openid-configuration
              issuer: "https://wt-repository.customer.de"
              authorization_endpoint: "https://wt-repository.customer.de/oauth/authorize"
              token_endpoint: "https://wt-repository.customer.de/oauth/token"
              revocation_endpoint: "https://wt-repository.customer.de/oauth/revoke"
              introspection_endpoint: "https://wt-repository.customer.de/oauth/introspect"
              userinfo_endpoint: "https://wt-repository.customer.de/oauth/userinfo"
              jwks_uri: "https://wt-repository.customer.de/oauth/discovery/keys"
            client:
              client_id: 9eb506b05101efaa5a8b4e52641c2db615288627c10b8d8fc0e6955493271b71
              client_secret: 745e662909db0dc88ee2906ac1238afce9dc7371b5bfd8402dc834d2fbcddba5
            scopes:
              - openid
            custom_authorization_parameters:
              access_type: offline
              prompt: consent
            custom_authorization_code_parameters: { }
            custom_refresh_parameters: { }
            custom_revoke_parameters: { }
            redirect_uri: https://eas.verivinum.com/oauth/callback
            features:
              cookie_expiry: false
              userinfo_expiry: true
              session_expiry: 1209600
              session_expiry_refresh_window: 86400
              session_retain_id: true
              refresh_access_token: true
              fetch_userinfo: true
              introspect_access_token: false
              introspect_expiry: 0
              authorization_token: access_token
              filtered_service_headers: [ ]
              logout:
                revoke_tokens_on_logout: [ ]
                end_provider_session:
                  enabled: false
                  post_logout_redirect_uri: https://eas.verivinum.com/oauth/end-session-redirect
                backchannel:
                  enabled: false
            assertions:
              exp: true
              nbf: true
              iss: true
            custom_service_headers:
              X-Forwarded-User:
                source: userinfo
                query_engine: jp
                query: $.email
                query_opts:
                  single_value: true
```

**Comment by kettenbach-it** [comment]
I just copied a working config with Gitlab as OAuth Server and replaced what needs to be replaced

**Comment by travisghansen** [comment]
Yeah lots of stuff wrong there, you will specifically need them to update the callback url on their end to `https://eas.verivinum.com/oauth/callback-ua-client-code`:

- `nonce` must be enabled
- `pkce` must be enabled
- I've added the `id_token_signature` assertion
- I've disabled `usserinfo` expiry
- disabled `refresh_access_token`
- enabled appropriate scopes for your custom service header

```
gitlab-customer:
      aud: Gitlab-Customer
      eas:
        plugins:
          - type: oidc
            issuer:
              #discover_url: https://wt-repository.customer.de/.well-known/openid-configuration
              issuer: "https://wt-repository.customer.de"
              authorization_endpoint: "https://wt-repository.customer.de/oauth/authorize"
              token_endpoint: "https://wt-repository.customer.de/oauth/token"
              revocation_endpoint: "https://wt-repository.customer.de/oauth/revoke"
              introspection_endpoint: "https://wt-repository.customer.de/oauth/introspect"
              userinfo_endpoint: "https://wt-repository.customer.de/oauth/userinfo"
              jwks_uri: "https://wt-repository.customer.de/oauth/discovery/keys"
            client:
              client_id: 9eb506b05101efaa5a8b4e52641c2db615288627c10b8d8fc0e6955493271b71
              client_secret: 745e662909db0dc88ee2906ac1238afce9dc7371b5bfd8402dc834d2fbcddba5
            nonce:
              enabled: true
              ttl: 600
            pkce:
              enabled: true
              code_challenge_method: S256
            scopes:
              - openid
              - email
              - profile
            redirect_uri: https://eas.verivinum.com/oauth/callback-ua-client-code
            features:
              cookie_expiry: false
              userinfo_expiry: false
              session_expiry: 1209600
              session_expiry_refresh_window: 86400
              session_retain_id: true
              refresh_access_token: false
              fetch_userinfo: true
              introspect_access_token: false
              introspect_expiry: 0
              authorization_token: access_token
              filtered_service_headers: [ ]
              logout:
                revoke_tokens_on_logout: [ ]
                end_provider_session:
                  enabled: false
                  post_logout_redirect_uri: https://eas.verivinum.com/oauth/end-session-redirect
                backchannel:
                  enabled: false
            assertions:
              # openid scope must be included to retrieve an id_token
              id_token_signature:
                enabled: true
                # defaults to issuer jwks endpoint, can be jwks response data or plain shared key/public key
                key: <PLACE KEY DATA HERE>
              exp: true
              nbf: true
              iss: true
            custom_service_headers:
              X-Forwarded-User:
                source: userinfo
                query_engine: jp
                query: $.email
                query_opts:
                  single_value: true
```
