### ISSUE TITLE
forward AUTH server is not working on https port

### ISSUE THREAD

**Issue by kashidsh1** [travisghansen/external-auth-server#160]
Thank you so much for the service. I have used this service recently in my test env.  we have a lot of our web services backed by traefik reverse proxy which is enabled for https. 

I ran the forward auth server in Kubernetes its running but accessed on HTTP only.  Is there a varient of this service or planned to run on HTTPS?  we want this service to access an HTTPS port.  Many Thanks

**Comment by travisghansen** [comment]
It can run on https https://github.com/travisghansen/external-auth-server#additional-env-vars

I assume you are referring to how it's accessed as an internal service within the cluster.

You can also expose `eas` over https obviously via traefik for external purposes (I use it that way with sso config for the cookies etc). I generally don't recommend pointing your auth config to an endpoint which goes through a reverse proxy as the headers getting passed etc can be tricky.

**Comment by kettenbach-it** [comment]
It's traefiks jobs to expose eas using https. 
For this to happen, you need to expose eas using the following IngressRoute:

```
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: eas-external
  namespace: traefik
spec:
  entryPoints:
    - https
  tls: {} # just use the wildcard certificate matching per domain 
  # or - if not existent - configure your own certificate:
#  tls:
#   secretName: your-tls-secret
  routes:
  - match: Host(`eas.yourdomain.com`) # Hostname to match
    kind: Rule
    services:
    - name: eas
      port: 80
```
