### ISSUE TITLE
/metrics end point still available to access after set disabled 

### ISSUE THREAD

**Issue by kashidsh1** [travisghansen/external-auth-server#175]
Hi there 
Because of security reasons, we have been asked to secure the /metrics endpoint.  There is a Ping endpoint also open, but as it is not displaying much sensitive information, the vulnerability of this endpoint is at low risk, /metrics endpoint vulnerability is at its high risk. 

To turn off the /metrics endpoint, we have tried setting monitoring to false as below 

```
monitoring:
  enabled: false
  serviceMonitor:
       enabled: false
```

This didn't help so we set the exporter to false, which again not helped. 
```
redis-ha:
  enabled: true
  auth: false
  redisPassword:
  exporter:
    enabled: false
  hardAntiAffinity: false
``` 

We don't know now, how we can turn off access to /metrics endpoint.  can somebody help us with this it's compromising our security and we can't go for live installation without solving this issue.   

Thank you so much for your help.
