### ISSUE TITLE
Allow passing unwrapped Userinfo headers

### ISSUE THREAD

**Issue by kevinoconnor7** [travisghansen/external-auth-server#5]
Currently X-Userinfo can be passed through to applications so that they have data about the logged in user. This data is a JSON-encoded blob.

However, I have some applications (ex. Grafana) that I can only configure to read a header (I can choose the name) that is either a username or e-mail; I cannot configure it to do any JSON parsing and unwrapping.

Would it be possible to add configuration that allows some Userinfo properties to be unwrapped into their own headers?

**Comment by travisghansen** [comment]
I've been thinking about that generally yeah. I think we can come up with something yeah.

Great that you're finding a fantastic use-case. If you could send over the specific grafana config you intend to use and separately what specific outcome you're after that would be great.

**Comment by kevinoconnor7** [comment]
```yaml
  grafana:
    image: grafana/grafana
    volumes:
      - /data/Configs/grafana:/var/lib/grafana
    networks:
      - internal
      - proxy
    links:
      - prometheus
      - influxsrv
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.backend=grafana"
      - "traefik.frontend.rule=Host:${GRAFANA_HOST}"
      - "traefik.port=3000"
      - "traefik.docker.network=reverseproxy_frontend"
      - "traefik.frontend.auth.forward.address=${FORWARD_AUTH_URL}"
      - "traefik.frontend.auth.forward.authResponseHeaders=X-Userinfo,X-Id-Token,X-Access-Token"
    environment:
      - GF_AUTH_PROXY_ENABLED=true
      - GF_AUTH_PROXY_HEADER_NAME=X-Forwarded-Email
      - GF_AUTH_PROXY_HEADER_PROPERTY=email
      - GF_AUTH_DISABLE_LOGIN_FORM=true
```
