### ISSUE TITLE
Keycloak OIDC Error

### ISSUE THREAD

**Issue by kruttik-lab49** [travisghansen/external-auth-server#65]
The following is my setup-
![Screen Shot 2020-03-12 at 4 32 35 PM](https://user-images.githubusercontent.com/51415807/76564545-19851e00-647f-11ea-80b4-f96952b5a4dc.png)

For the most part the redirects seems to be working. It fails on the `external auth server` retrieving tokens.
```
{"service":"external-auth-server","level":"verbose","message":"audMD5: 8708765772d4ac341e8f85effde0c452"}
{"service":"external-auth-server","level":"verbose","message":"cookie name: _eas_oauth_session"}
{"service":"external-auth-server","level":"verbose","message":"decoded state: {\"request_uri\":\"http://nexus.sandbox.xxxx.com/\",\"aud\":\"8708765772d4ac341e8f85effde0c452\",\"csrf\":\"c8f2c9ca-27b5-4818-a2ed-9692d32b2133\",\"req\":{\"headers\":{}},\"request_is_xhr\":false,\"iat\":1583963627}"}
{"service":"external-auth-server","level":"verbose","message":"audMD5: 8708765772d4ac341e8f85effde0c452"}
{"service":"external-auth-server","level":"verbose","message":"cookie name: _eas_oauth_session"}
{"message":"begin token fetch with authorization code","level":"verbose","service":"external-auth-server"}
{"service":"external-auth-server","level":"verbose","message":"compare_redirect_uri: https://eas.sandbox.xxxxx.com/oauth/callback"}
{"message":"failed to retrieve tokens","level":"verbose","service":"external-auth-server"}
{"level":"error","service":"external-auth-server","message":"Unexpected token P in JSON at position 0","stack":"SyntaxError: Unexpected token P in JSON at position 0\n    at JSON.parse (<anonymous>)\n    at authenticatedPost.then.then.response (/home/eas/app/node_modules/openid-client/lib/client.js:801:43)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"}
```

keycloak client settings-
![Screen Shot 2020-03-12 at 4 37 46 PM](https://user-images.githubusercontent.com/51415807/76565021-20606080-6480-11ea-8d15-7d4b5fefdedb.png)

Here's the config_token:
```yaml
{
        type: "oidc",
        issuer: {
          discover_url: http://keycloak.xxxx.com/auth/realms/master/.well-known/uma2-configuration,
        },
        client: {
          client_id: "eas",
          client_secret: "xxxx"

        },
        scopes: ["openid", "email", "profile"], // must include openid
        redirect_uri: "https://eas.xxxx.com/oauth/callback",
        features: {
          cookie_expiry: false,

          userinfo_expiry: true,

          session_expiry: true,
          session_expiry_refresh_window: 86400,

          session_retain_id: true,

          refresh_access_token: true,

          fetch_userinfo: true,

          introspect_access_token: false,

          authorization_token: "access_token"
        },
        assertions: {
          exp: true,

          nbf: true,

          iss: true,

        },
        cookie: {
          domain: "xxxx.com", //defaults to request domain, could do sso with more generic domain
        },
        headers: {},
      }
```

**Comment by kruttik-lab49** [comment]
Here's the config_token:
```yaml
{
        type: "oidc",
        issuer: {
          discover_url: http://keycloak.xxxx.com/auth/realms/master/.well-known/uma2-configuration,
        },
        client: {
          client_id: "eas",
          client_secret: "xxxx"

        },
        scopes: ["openid", "email", "profile"], // must include openid
        redirect_uri: "https://eas.xxxx.com/oauth/callback",
        features: {
          cookie_expiry: false,

          userinfo_expiry: true,

          session_expiry: true,
          session_expiry_refresh_window: 86400,

          session_retain_id: true,

          refresh_access_token: true,

          fetch_userinfo: true,

          introspect_access_token: false,

          authorization_token: "access_token"
        },
        assertions: {
          exp: true,

          nbf: true,

          iss: true,

        },
        cookie: {
          domain: "xxxx.com", //defaults to request domain, could do sso with more generic domain
        },
        headers: {},
      }
```

**Comment by travisghansen** [comment]
Looking at the logs it appears to be an issue when `eas` tries to retrieve the tokens using the `code` returned after login. What happens is that `eas` receives the `code` (via `GET` param) and then turns around and makes an API call to the `oidc` provider to get a `tokenSet`. This is the `Authorization Code Flow` anyhow which is what `eas` implements. To make that request I'm simply using a library (https://github.com/panva/node-openid-client) which handles all the spec speaking generally. I'm guessing based on the response/error `keycloak` doesn't like that request for some reason.

The only differences I have from you in my keycloak setup on that screen is I left `Root URL`, `Admin URL`, and `Web Origins` blank. Of the 3 the only thing I can imagine that may have any impact would be the `Web Origins` field. Can you try to remove that and give it another go?

A couple options:

- Do you have/see any logs from keycloak that look related?
- Try deploying `eas` with `NODE_DEBUG=request` env var set. You *may* get some extra stuff spewing out to give some insight what keycloak doesn't like.

**Comment by kruttik-lab49** [comment]
On it.

**Comment by kruttik-lab49** [comment]
I think I see the problem. HTTP->HTTPS redirection I think. 

Here's the NODE_DEBUG log-
```
REQUEST { method: 'POST',
  url:
   'http://auth.xxxxxx.com/auth/realms/master/protocol/openid-connect/token',
  headers:
   { 'User-Agent':
      'openid-client/2.5.0 (https://github.com/panva/node-openid-client)',
     Accept: 'application/json',
     Authorization:
      'Basic xxxxxx' },
  form:
   { grant_type: 'authorization_code',
     code:
      '1xxxx',
     redirect_uri: 'https://eas.xxxxxx.com/oauth/callback' },
  followRedirect: false,
  timeout: 10000,
  callback: [Function] }
REQUEST make request http://auth.xxxx.com/auth/realms/master/protocol/openid-connect/token
REQUEST onRequestResponse http://auth.xxxxx.com/auth/realms/master/protocol/openid-connect/token 308 { 'content-type': 'text/plain; charset=utf-8',
  date: 'Thu, 12 Mar 2020 21:39:09 GMT',
  location:
   'https://auth.xxxxx.com/auth/realms/master/protocol/openid-connect/token',
  'content-length': '18',
  connection: 'Close' }
REQUEST redirect https://auth.xxxxx.com/auth/realms/master/protocol/openid-connect/token
REQUEST reading response's body
REQUEST finish init function http://auth.sandbox.kube.lab49aws.com/auth/realms/master/protocol/openid-connect/token
REQUEST response end http://auth.sandbox.kube.lab49aws.com/auth/realms/master/protocol/openid-connect/token 308 { 'content-type': 'text/plain; charset=utf-8',
  date: 'Thu, 12 Mar 2020 21:39:09 GMT',
  location:
   'https://auth.xxxx.com/auth/realms/master/protocol/openid-connect/token',
  'content-length': '18',
  connection: 'Close' }
REQUEST end event http://auth.xxxx.com/auth/realms/master/protocol/openid-connect/token
REQUEST has body http://auth.xxxx.com/auth/realms/master/protocol/openid-connect/token 18
REQUEST emitting complete http://auth.xxxx.com/auth/realms/master/protocol/openid-connect/token
```

Notice that the protocol is `http`. 

Here's the keycloak OIDC discovery json. Notice that the URLs are `https`:
```json
{
  "issuer": "https://auth.xxxxx.com/auth/realms/master",
  "authorization_endpoint": "https://auth.xxxxx.com/auth/realms/master/protocol/openid-connect/auth",
  "token_endpoint": "https://auth.xxxxx.com/auth/realms/master/protocol/openid-connect/token",
  "token_introspection_endpoint": "https://auth.xxxxx.com/auth/realms/master/protocol/openid-connect/token/introspect",
  "end_session_endpoint": "https://auth.xxxxx.com/auth/realms/master/protocol/openid-connect/logout",
  "jwks_uri": "https://auth.xxxxx.com/auth/realms/master/protocol/openid-connect/certs",
  "grant_types_supported": [
    "authorization_code",
    "implicit",
    "refresh_token",
    "password",
    "client_credentials"
  ],
  "response_types_supported": [
    "code",
    "none",
    "id_token",
    "token",
    "id_token token",
    "code id_token",
    "code token",
    "code id_token token"
  ],
  "response_modes_supported": [
    "query",
    "fragment",
    "form_post"
  ],
  "registration_endpoint": "https://auth.xxxxx.com/auth/realms/master/clients-registrations/openid-connect",
  "token_endpoint_auth_methods_supported": [
    "private_key_jwt",
    "client_secret_basic",
    "client_secret_post",
    "tls_client_auth",
    "client_secret_jwt"
  ],
  "token_endpoint_auth_signing_alg_values_supported": [
    "PS384",
    "ES384",
    "RS384",
    "ES256",
    "RS256",
    "ES512",
    "PS256",
    "PS512",
    "RS512"
  ],
  "scopes_supported": [
    "openid",
    "address",
    "email",
    "microprofile-jwt",
    "offline_access",
    "phone",
    "profile",
    "roles",
    "web-origins"
  ],
  "resource_registration_endpoint": "https://auth.xxxxx.com/auth/realms/master/authz/protection/resource_set",
  "permission_endpoint": "https://auth.xxxxx.com/auth/realms/master/authz/protection/permission",
  "policy_endpoint": "https://auth.xxxxx.com/auth/realms/master/authz/protection/uma-policy",
  "introspection_endpoint": "https://auth.xxxxx.com/auth/realms/master/protocol/openid-connect/token/introspect"
}
```
It appears that the `external auth server` does not follow redirect and/or it could be something to do with `X_FORWARDED_PROTO` headers?

**Comment by kruttik-lab49** [comment]
I guess I can always change the oidc config from
this:
```yaml
issuer: {
          discover_url: http://keycloak.xxxx.com/auth/realms/master/.well-known/uma2-configuration,
        }
```
to
```yaml
issuer: {
          /**
           * via manual definition
           */
          //issuer: 'https://accounts.google.com',
          //authorization_endpoint: 'https://accounts.google.com/o/oauth2/v2/auth',
          //token_endpoint: 'https://www.googleapis.com/oauth2/v4/token',
          //userinfo_endpoint: 'https://www.googleapis.com/oauth2/v3/userinfo',
```

Do you think it's worth trying?
