### ISSUE TITLE
Undefined in return from eas

### ISSUE THREAD

**Issue by autarchprinceps** [travisghansen/external-auth-server#89]
Similar to #23 we are trying to get eas to work with Traefik v2. We are using github and the redirect to and login into github worked as expected, but once logged in, the return URL has undefined in it. But unlike #23 it is in the path, not URL. Something like https://eas.example.com/undefined?__eas_oauth_handler__=authorization_callback&code=...&state=...

From what we understood from previous similar errors, was that X-Forwarded headers being dismissed was an issue. We tried to debug this, by replacing eas containers with mendhak/http-https-echo, which just echos und logs requests with all headers and details. Just replacing the container, it does get x-forwarded headers.

```
{ path: '/',
  headers: 
   { host: 'eas.example.com',
     'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.80 Safari/537.36',
     accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
     'accept-encoding': 'gzip, deflate, br',
     'accept-language': 'en-GB,en;q=0.9,en-US;q=0.8,de;q=0.7',
     'cache-control': 'no-cache',
     dnt: '1',
     pragma: 'no-cache',
     'sec-fetch-dest': 'document',
     'sec-fetch-mode': 'navigate',
     'sec-fetch-site': 'none',
     'upgrade-insecure-requests': '1',
     'x-forwarded-for': '1.2.3.4'',
     'x-forwarded-host': 'eas.example.com'',
     'x-forwarded-port': '443',
     'x-forwarded-proto': 'https',
     'x-forwarded-server': 'traefik-56b55bb5f9-9spwg',
     'x-real-ip': '1.2.3.4'' },
  method: 'GET',
  body: '',
  cookies: undefined,
  fresh: false,
  hostname: 'eas.example.com',
  ip: '1.2.3.4',
  ips: [ '1.2.3.4' ],
  protocol: 'https',
  query: {},
  subdomains: [ 'eas' ],
  xhr: false,
  os: { hostname: 'external-auth-server-6c54fbc87f-rzkx2' },
  connection: { servername: undefined } }
```

This is our middleware. Without it our Testingress returns 200 and a simple response page. We are using a normal Ingress with traefik.ingress.kubernetes.io/router.middlewares: traefik-github-oauth@kubernetescrd as annotation.
```yaml
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: github-oauth
  namespace: traefik
spec:
  forwardAuth:
    address: https://eas.example.com/verify?config_token_id=...&config_token_store_id=primary
    authResponseHeaders:
    - X-Userinfo
    - X-Id-Token
    - X-Access-Token
    - Authorization
    trustForwardHeader: true
```

Do you have any insight, why it would return undefined as path, or what we could attempt to fix that? I cannot see any issues in the eas logs, and with Traefik v1 the same eas was working. We have tried with the old 0.6.0 image, we were using for some time without many issues, and upgrading to 0.9.1, which I believe is the newest currently available.
